Fix for #284
code4romania/war-support-sprijin-de-urgenta-client pull request #290
Opened 2022-03-07 21:01 UTC by cotaoctavian

### What does it fix?
Fix for #284 

Closes #284

### How has it been tested?
![image](https://user-images.githubusercontent.com/45451082/157117015-0ac5171d-b40f-4e43-9864-1915bae81511.png)
![image](https://user-images.githubusercontent.com/45451082/157117049-e9767aaf-9319-4b0d-8e3f-11f61d99dd52.png)
![image](https://user-images.githubusercontent.com/45451082/157117097-70ae4ba1-80e2-440d-8dd0-46dd320918e3.png)
![image](https://user-images.githubusercontent.com/45451082/157116985-8fb7aacd-488b-43ee-8ea0-207e7b676163.png)
![image](https://user-images.githubusercontent.com/45451082/157117135-2ca23cf6-f1db-47ce-b9cb-58453a19ba15.png)

2022-03-07 21:14 UTC, idormenco requested changes

2022-03-07 21:14 UTC, idormenco commented on public/locales/ru/common.json
> +  "error.capacity.moreThanZero": "Минимальная принимаемая сумма 1",
this is not a correct translation

2022-03-07 21:18 UTC, idormenco commented on public/locales/ru/common.json
> +  "error.capacity.moreThanZero": "Минимальная принимаемая сумма 1",
we will provide correct translations

2022-03-08 09:25 UTC, rhadu commented
issue closed by #289

2022-03-08 09:25 UTC, closed without merging