Add validation on "to" interval time to be greater than "from"
code4romania/war-support-sprijin-de-urgenta-client pull request #312
Opened 2022-03-09 10:00 UTC by costinicolescu

### What does it fix?

Closes #270  

Validation for `availability_interval_to` was added to be greater than `availability_interval_from`.
New text was added.
### How has it been tested?
I tried some time before and after the "FROM" time in the "TO" time picker.

2022-03-09 10:23 UTC, idormenco requested changes

2022-03-09 10:23 UTC, idormenco commented on forms/offer/transport/OfferTransportGoodsForm.tsx
> +    availability_interval_to: yup.mixed().typeError(t('error.must.be.time'))
1. this validation should be added in `OfferTransportPersonsForm.tsx` also
2. please extract this validator in `validators.ts` see `dateStringValidator` or `dateInTheFutureValidator`

2022-03-09 10:23 UTC, idormenco commented on public/locales/ru/common.json
> +  "error.must.be.greater.than.from": "Until value must be greater than From",
you can remove this line and we will provide translation

2022-03-09 10:23 UTC, idormenco commented on public/locales/ua/common.json
> +  "error.must.be.greater.than.from": "Until value must be greater than From",
you can remove this line and we will provide translation

2022-03-14 19:59 UTC, cipick approved these changes
LGTM

2022-03-14 20:13 UTC, idormenco approved these changes

2022-03-14 20:13 UTC, merged